/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_spiritlight_chess_fish_internal_jnative_MagicBitboard */

#ifndef _Included_com_spiritlight_chess_fish_internal_jnative_MagicBitboard
#define _Included_com_spiritlight_chess_fish_internal_jnative_MagicBitboard
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_spiritlight_chess_fish_internal_jnative_MagicBitboard
 * Method:    queen
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_spiritlight_chess_fish_internal_jnative_MagicBitboard_queen
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_spiritlight_chess_fish_internal_jnative_MagicBitboard
 * Method:    rook
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_spiritlight_chess_fish_internal_jnative_MagicBitboard_rook
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_spiritlight_chess_fish_internal_jnative_MagicBitboard
 * Method:    bishop
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_spiritlight_chess_fish_internal_jnative_MagicBitboard_bishop
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
