/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_rainvaporeon_chess_fish_internal_jnative_MagicBitboard */

#ifndef _Included_io_github_rainvaporeon_chess_fish_internal_jnative_MagicBitboard
#define _Included_io_github_rainvaporeon_chess_fish_internal_jnative_MagicBitboard
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_rainvaporeon_chess_fish_internal_jnative_MagicBitboard
 * Method:    queen
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_io_github_rainvaporeon_chess_fish_internal_jnative_MagicBitboard_queen
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     io_github_rainvaporeon_chess_fish_internal_jnative_MagicBitboard
 * Method:    rook
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_io_github_rainvaporeon_chess_fish_internal_jnative_MagicBitboard_rook
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     io_github_rainvaporeon_chess_fish_internal_jnative_MagicBitboard
 * Method:    bishop
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_io_github_rainvaporeon_chess_fish_internal_jnative_MagicBitboard_bishop
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
