/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_rainvaporeon_chess_fish_internal_jnative_NativeMagicBoard */

#ifndef _Included_io_github_rainvaporeon_chess_fish_internal_jnative_NativeMagicBoard
#define _Included_io_github_rainvaporeon_chess_fish_internal_jnative_NativeMagicBoard
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_rainvaporeon_chess_fish_internal_jnative_NativeMagicBoard
 * Method:    queen
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_io_github_rainvaporeon_chess_fish_internal_jnative_NativeMagicBoard_queen
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     io_github_rainvaporeon_chess_fish_internal_jnative_NativeMagicBoard
 * Method:    rook
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_io_github_rainvaporeon_chess_fish_internal_jnative_NativeMagicBoard_rook
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     io_github_rainvaporeon_chess_fish_internal_jnative_NativeMagicBoard
 * Method:    bishop
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_io_github_rainvaporeon_chess_fish_internal_jnative_NativeMagicBoard_bishop
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
